### ISSUE TITLE
Error in KrigR

### ISSUE THREAD

**Issue by poniitty** [ErikKusch/KrigR#1]
Hi,

Thanks for a very useful package!

However, I run into some problems while trying to replicate the KrigR workshop script or the example code for the krigR-function. I managed to download and preprocess all the ERA and DEM data but when trying to complete the actual kriging R gives me an error:

`Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'res': object 'cropped_train' not found`

I tried to update all the packages and look into the source code with no success. Do you happen to have any idea about the reason for this problem?

Thanks,
Pekka

R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

**Comment by ErikKusch** [comment]
Hi Pekka, 

really basic error on my end. "cropped_train" is one of my troubleshooting data sets. When I fixed one of the internal KrigR functions, I left that in there. I have fixed the issue in my latest commit. 

Sorry for the inconvenience and thank you so much for bringing this up!
