### ISSUE TITLE
Unreachable GMTED2010 Viewer

### ISSUE THREAD

**Issue by lazarus394** [ErikKusch/KrigR#2]
The code is working perfectly when the input data (ERA dataset and GMTED2010 dataset) are provided. The problem arises when the input data is not provided, which is the case when the CDS API or the GMTED2010 Viewer is unavailable. Since the ERA dataset is vast, it's impossible to provide the dataset to treat this issue. However, that is not a large issue, because the CDS API is stable. On the other hand, the GMTED2010 Viewer is often unavailable. The data downloaded from the GMTED2010 is also static, meaning that the same dataset is used for every possible case. Therefore, I suggest adding the GMTED2010.zip file to the directory. The .zip file should be extracted in the GMTED2010 folder, and this addition makes the code more robust and independent of the USGS sites.

**Comment by ErikKusch** [comment]
Hi Lazarus, 
thanks for the input on this. I am currently looking into this issue, but seem to be unable to provide the GMTED data with the package via GitHub since it exceeds the allowed file size for uploads to GitHub. I am looking into alternative hosting as a temporary solution. If anyone has some input on this, I am glad to take it!

**Comment by lazarus394** [comment]
Hi Erik,

You're welcome! I think that the best option is to create a Google Drive folder dedicated to KrigR and upload the GMTED data there. The dataset can be made publicly available so that anyone who wants to use the code can also download it without any problems.

**Comment by ErikKusch** [comment]
Issue has been resolved with commit 2dba32 (see reference above this comment) by implementing an additional argument called `Source` to the `download_DEM` function and the `krigR` function. Set this argument to `"Drive"` to obtain GMTED 2010 data from a dropbox with a static copy of the USGS GMTED 2010 data as obtained today (04/01/20).
