### ISSUE TITLE
Add a parameter that prevents to save the final kriged product

### ISSUE THREAD

**Issue by ShinyFabio** [ErikKusch/KrigR#20]
Hi again,
I have a suggestion for you. I think could be useful to add a parameter in `krigR()` that tells if you want to save the products. For example, in my case, I launch the `krigR()` function and save the output in a variable. After that, I immediately modify the output and finally save everything as a .mat. In my case saving the .nc file is totally useless to me.  

I've already added this enhancement to my fork if you want to have a look. It needs only the recompilation of the documents and the change in the FileName variable (if you don't save anything you should not provide a file name).

**Comment by ErikKusch** [comment]
Heya,

great idea. I am shelving this for now and adding it to my list of development goals / ideas. I plan to pick up more development again soon and will keep this at the top of my list. As the inclusion of this parameter would require rewriting of my workshop material, I am holding off on it for now.

Please keep additional development ideas and requests coming.

**Comment by ErikKusch** [comment]
Resolved on development version with 31ae996d17f47c9ea2a87f8f589338db41d77ddf
