### ISSUE TITLE
Efficiency improvements

### ISSUE THREAD

**Issue by ErikKusch** [ErikKusch/KrigR#25]
General stability:
- unload `tidyverse` to avoid parallel processing errors and reload on exit

Switch spatial object handling to:
- `terra` (terra dev version on MacOS (install.packages("terra", repos = "https://rspatial.r-universe.dev")))
- `sf`

Dependencies:
- re-code for importing functions from packages rather than hard dependencies.

Download improvements:
- [Done, DevelopVersion] update `SingularDL` range
- [Done, DevelopVersion] update `SingularDL` date selection for downloads
- automatic handling of dataset-variable specific issues (such as missing hours at beginning of reanalysis period, see also metadata ideas in #26. This is currently causing errors for some users: #35)
- make download segments of `SingularDL` length default rather than month segments, also: consider breaking large queries into maximum chunks for download and aggregation on individual cores
- handling of data stack (spatial limitting and temporal aggregating) across several cores if possible
- [Done, DevelopVersion] specify hour ranges as mentioned in #53 
- [Done, DevelopVersion] enable aggregates at `TResolution >= "month"` when `TStep = 1` (currently only monthly means are used for speedier processing)

File handling:
- [Done] find a way of saving time-stamps to NETCDFs
- [Done, DevelopVersion] check if target files exist for download and kriging functions

Ease-of-Use:
- [Done, DevelopVersion] improved input validation (e.g., case-sensitivity of inputs, see #52)

**Comment by Simply-Adi** [comment]
Reiterating an already cited issue for a speedy redressal. @ErikKusch 
File handling:
-find a way of saving time-stamps to NETCDFs

**Comment by ErikKusch** [comment]
Hey @Simply-Adi,

thanks for taking this issue from Email to Github as prompted. Unfortunately, my current job tasks do not include `KrigR` development hence why I cannot address requests for additional functionality "speedily". I will however, strive to resolve bugs as quickly as possible.

That being said, when troubleshooting your request on my own time, I found a bug and when resolving it decided to also implement your request.

With this [pull](https://github.com/ErikKusch/KrigR/pull/39) between my development and main branch, I have implemented saving of time-stamps to the saved NETCDFs. These are found as the "time" field and index the first date/hour of every aggregation interval. With the [additional pull](https://github.com/ErikKusch/KrigR/pull/40) just now, I am propagating these as layer names into the Kriging output.

## Minimal Working Example
```r
library(KrigR)
Extent_ext <- extent(c(9.87, 15.03, 49.89, 53.06))
QS_Raw <- download_ERA(
  Variable = "2m_temperature",
  DataSet = "era5",
  DateStart = "1940-01-02",
  DateStop = "1940-01-04",
  TResolution = "day",
  TStep = 1,
  Extent = Extent_ext,
  FileName = "Test",
  API_User = API_User,
  API_Key = API_Key
)
``` 
### Base integration
As `KrigR` still relies largely on the `raster` library, here is how the time stamps are currently being reported with the object returned in `R` directly:
```r
QS_Raw
```

```
class      : RasterStack 
dimensions : 9, 13, 117, 3  (nrow, ncol, ncell, nlayers)
resolution : 0.5, 0.5  (x, y)
extent     : 9.12, 15.62, 49.14, 53.64  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs 
names      : X1940.01.02, X1940.01.03, X1940.01.04 
```

### `terra` reading
Loading the saved NETCDF into `R` with `terra` functionality:
```r
terra::rast("Test.nc")
```
You see the time field reporting the time stamps now:

```
class       : SpatRaster 
dimensions  : 9, 13, 3  (nrow, ncol, nlyr)
resolution  : 0.5, 0.5  (x, y)
extent      : 9.12, 15.62, 49.14, 53.64  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
source      : Test.nc 
varname     : 2m_temperature 
names       : 2m_temperature_1, 2m_temperature_2, 2m_temperature_3 
time        : 1940-01-02 to 1940-01-04 UTC 
```

### Python
I know you are continuing data handling in python. As this is an `R` package first and foremost, I am afraid I did not check whether this fix applies to Python. Happy to hear back from you.

**Comment by Simply-Adi** [comment]
Apologies for the late reply. Thank you for the valuable update. 

I have tested and verified the changes. Once again, thank you!

**Comment by ErikKusch** [comment]
All remaining development goals herein have been moved to individual issues for better tracking of development progress.
