### ISSUE TITLE
ERA5 reanalysis data back to 1940

### ISSUE THREAD

**Issue by japilo** [ErikKusch/KrigR#33]
The Copernicus data store now includes [ERA5 hourly data reanalysis going back to 1940](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels). However, all documentation I have read for this package indicates that it only includes data back to 1950. Can functionality be added to include the 1940-1950 data?

**Comment by ErikKusch** [comment]
Hi @japilo , thanks for alerting me to that.

You will be happy to hear that the `KrigR` functionality already supports this. I just tested this query (adapted from the [Quick Start](https://www.erikkusch.com/courses/krigr/quickstart/) section of my workshop material)  and it ran without issue:

```r
Extent_ext <- extent(c(9.87, 15.03, 49.89, 53.06))
QS_Raw <- download_ERA(
  Variable = "2m_temperature",
  DataSet = "era5",
  DateStart = "1940-01-02",
  DateStop = "1940-01-04",
  TResolution = "day",
  TStep = 1,
  Extent = Extent_ext,
  FileName = "Test",
  API_User = API_User,
  API_Key = API_Key
)
```

**Comment by ErikKusch** [comment]
I will need to figure out ways to update the documentation based off of such changes. I reckon I can do so, once I implement  #26.
