### ISSUE TITLE
Error in `purrr::when` when Cores > 1

### ISSUE THREAD

**Issue by japilo** [ErikKusch/KrigR#34]
I got the following error when I attempted to download data using multiple cores in `BioClim`:

`Error in `when()`:
! At least one matching condition is needed.
Backtrace:
 KrigR::BioClim(...)
 purrr::when(...)`

I believe I know what this error comes from. There is a `purrr::when` call in the `BioClim` code when Cores > 1. `purrr::when` requires the value being evaluated as the first argument, as discussed [here](https://stackoverflow.com/questions/72096879/purrrwhen-doesnt-evaluate-first-condition) on Stack Exchange.

**Comment by ErikKusch** [comment]
I have not seen a `purr` specific issue before, but I know that the `doParallel` library I use for parallelizing code runs into issues like these when the `tidyverse` is loaded. Can you please supply an MWE to recreate this issue?

**Comment by japilo** [comment]
Interesting. It does seem to be having `tidyverse` loaded that causes the error. The following code threw an error when I had `tidyverse` loaded and no error when I didn't have it loaded:

`BioClim(Water_Var = "total_precipitation",
        Y_start = "1940",
        Y_end = "1941",
        T_res = 'day',
        Extent = bbox,
        DataSet = 'era5',
        Dir = Dir,
        verbose = TRUE,
        FileName = 'BioClim_1940.nc',
        API_User = API_User,
        API_Key = API_Key,
        Cores = 8)`

**Comment by ErikKusch** [comment]
Fab, I am already planning to implement a workaround (see #25). Bumping it up on my to-do.
