### ISSUE TITLE
Question about krigR capabilities

### ISSUE THREAD

**Issue by Doltrix** [ErikKusch/KrigR#41]
Hello again, sir.
I have a question...
Is it possible to plot uncertainty maps with krigR? 
Let me explain. I am looking to increase the number of sensors of a given meteorological variable existing in a sector by kriging. I have as resources the location of my current stations and the information downloaded from ERA5 using krigR, I would like from these two elements to find uncertainty maps to verify the possible locations of new sensors.
Thanks again.

**Comment by ErikKusch** [comment]
Hiya,

to my understanding, what you are asking should be covered by [dynamic data uncertainty](https://www.erikkusch.com/courses/krigr/download/#dynamical-data-uncertainty).

Does that fulfill your needs?

**Comment by ErikKusch** [comment]
Given the inactivity on this issue, I will mark this as closed for now. Feel free to ping again if the above did not satisfy your question.
