### ISSUE TITLE
download_DEM: filename for target DEM is incorrect

### ISSUE THREAD

**Issue by sambo1972** [ErikKusch/KrigR#46]
The filename at this line (https://github.com/ErikKusch/KrigR/blob/243c8768ac6b91ccb87e4f792eca75f854e5614a/R/download.R#L617C75-L617C75) 
is the same as in the previous line - i.e. : "GMTED2010_Train.nc".

Consequently the training file is immediately overwritten with the target DEM - looks like a simple copy & paste error.

**Comment by ErikKusch** [comment]
Hiya Sam,

thanks for pointing this out. Could you give me additional information where you ran into that issue? It looks like this would be in the training material?

Cheers,
Erik

**Comment by ErikKusch** [comment]
Nevermind - I should have just clicked the link you provided :-D Thank you very much for this. Issue is fixed with #47. Reinstalling will provide you with the fix. Thank you so much!
