### ISSUE TITLE
Time window

### ISSUE THREAD

**Issue by rfsaldanha** [ErikKusch/KrigR#53]
Hi! An interesting feature would be the ability to restrain the download function to a certain time window. This will make possible to have daily aggregates for diurnal or nocturnal hours, by example. 

Thanks for the package!

**Comment by ErikKusch** [comment]
Thanks for the suggestion. I have placed it into the development list as seen in the linked issues. I will close this issue now and keep track of implementing this via the other two.

Cheers :-)

**Comment by ErikKusch** [comment]
Implemented in release [v0.2.0](https://github.com/ErikKusch/KrigR/releases/tag/Dev).

I do not plan to implement download of specific hours across several days as of right now. I recommend writing wrappers for this purpose.
