### ISSUE TITLE
Problem with keyring password

### ISSUE THREAD

**Issue by INDEINS** [ErikKusch/KrigR#56]
Hi Erick  

I am tried to use the KrigR. 

![image](https://github.com/ErikKusch/KrigR/assets/138617344/fa6eee84-d839-44d4-9da5-b5f7b80a1f3c)

but the R show me for put a password 

![image](https://github.com/ErikKusch/KrigR/assets/138617344/6edd9616-0b4e-46dd-af44-8413e3d05595)

I put my password of https://cds.climate.copernicus.eu/user/ but is not work 

Please, probably can you send anay recommendation

**Comment by ErikKusch** [comment]
Ah yes - this is a Mac Issue - please type the password you log onto your Mac with into that box. You can stop this popup by allowing keyring access for R (unfortunately, this only works when running in sequential order on downloads).

**Comment by INDEINS** [comment]
I am using a Rstudio-server mount in a linux server.

**Comment by ErikKusch** [comment]
Have you tried entering your user password? Linux or mac - the underlying infrastructure is often the same.

**Comment by INDEINS** [comment]
Yes I tried, recenctly with your response. But is not work jet.

**Comment by ErikKusch** [comment]
As this is not a KrigR issue itself but rather a linux-issue, please try troubleshooting along these lines first: https://askubuntu.com/questions/867/how-can-i-stop-being-prompted-to-unlock-the-default-keyring-on-boot. It might also be useful to contact your server admin.

Please let me know if you find a solution.

**Comment by ErikKusch** [comment]
Hiya - I went digging a bit in some of my older applications of KrigR. In one particular linux-based HPC environment, I had to run `export R_KEYRING_BACKEND="env"` in the terminal outside of R or Studio to get downloads to work. Maybe try that?
