### ISSUE TITLE
install error (rgdal)

### ISSUE THREAD

**Issue by fipoucat** [ErikKusch/KrigR#73]
I am trying to install KrigR on Rstudio (Mac) but getting an error related to rgdal (to the best of my knowledge, it is retired).

configure: Install failure: compilation and/or linkage problems.
configure: error: GDALAllRegister not found in libgdal.
ERROR: configuration failed for package ‘rgdal’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/rgdal’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/rgdal’

**Comment by ErikKusch** [comment]
Hiya,

this is unfortunately a re-occuring issue (#59). You can resolve this issue in one of two ways:

1. Follow the guideline given on the [landing page on KrigR GitHub](https://github.com/ErikKusch/KrigR) or the [KrigR Workshop material](https://www.erikkusch.com/courses/krigr/setup/) and install `rgdal` by hand by running:

```r 
remotes::install_github("https://github.com/cran/rgdal")
```

2. Install the latest version of `KrigR` from the development branch and use the novel `CDownloadS(...)` function introduced therein. You can do so by running:

```r
devtools::install_github("https://github.com/ErikKusch/KrigR", ref = "Development")
```

Note that this version of `KrigR` is under development and does only contain functionality for data download (what `download_ERA(...)` does in the stable release) and does not currently support any kriging.
