### ISSUE TITLE
Any way to use KrigR to download universal thermal climate index (UTCI) from ERA5-HEAT?

### ISSUE THREAD

**Issue by sdnyadanu** [ErikKusch/KrigR#84]
Hi @ErikKusch 
Big congratulations to you and the team for the KrigR package. 
This is not a bug anyway.
I want to use the package to download universal thermal climate index (UTCI) from the ERA5-HEAT (Human thErmAl comforT) data ([Thermal comfort indices derived from ERA5 reanalysis] (https://cds.climate.copernicus.eu/datasets/derived-utci-historical?tab=overview)) but was unable to and realised that UTCI dataset or ERA5-HEAT is not included in the acceptable datasets or variables.

Please, is there any possible way to use KrigR package to download the UTCI?

Thank you.
Regards,
Sylvester

**Comment by ErikKusch** [comment]
Hi Sylvester,

at present there is not, I am afraid. You can open a feature request if you want to. I just browsed the description of the data set you linked and it would not be too much hassle to implement. Unfortunately, however, I am pretty swamped at present and am conceptualising the creation of a new and improved climate data toolbox.

To implement this dataset with KrigR, I will need a metadata file for this product. The existing ones have been provided by @RichardDavy84 - any chance you could procure one? If Richard is not available to do it, could I ask you, @sdnyadanu to do so? You'll see how metadata for CDS products is registered with KrigR [here](https://github.com/ErikKusch/KrigR/tree/master/metadata). Once you have created an R script that creates the .RData file containing a list object of metadata of the data set you are after, please submit this in a CDS Metadata Issue here.

Cheers,
Erik

**Comment by sdnyadanu** [comment]
Hi Erik,
Okay.
I have not done it before but will see how metadata files could be added.
Many thanks.

Cheers,
Sylvester

**Comment by RichardDavy84** [comment]
Hi Sylvester,

If you are in a hurry I suggest downloading the ERA5-HEAT data using the online portal (https://cds.climate.copernicus.eu/datasets/derived-utci-historical?tab=download), and then using KrigR to do the downscaling using your desired co-variates.

Best, Richard

**Comment by sdnyadanu** [comment]
Hi Richard,
Yes, I tried downloading using the online portal but having problems with
it. I downloaded it with the R package ‘ecmwfr’ but the file appears
corrupted and not accessible after several attempts.

Thank you.
Regards,
Sylvester

**Comment by ErikKusch** [comment]
Closing this for now due to inactivity. Happy to re-open if things change.
