### ISSUE TITLE
Wont download data

### ISSUE THREAD

**Issue by dwittig1** [ErikKusch/KrigR#85]
It just endlessly says waiting for cds to start processing the query

**Comment by ErikKusch** [comment]
Depending on CDS queue this might take some time and is expected behaviour.

Please head to https://cds.climate.copernicus.eu/requests?tab=all and check whether your download(s) ha(s/ve) been queried there. Assuming so, I will close this issue.

**Comment by dwittig1** [comment]
Interesting, it has been queried but has been i queu for almost 24 hours. Do you find if you download too many years at once it bogs down?

**Comment by ErikKusch** [comment]
Depending on how much you queue (size of individual requests and number of them) as well as how much others queue, wait times can unfortunately fluctuate a lot. That being said, I rarely experience wait times that long, but I have expected some instability on the CDS end recently. Maybe delete the queued requests in the CDS web portal and re-run the KrigR command?

**Comment by dwittig1** [comment]
thats a good idea, this is the error message received so that may be the issue Number of queued requests using the API is limited to 200. Please configure your scripts accordingly. visit copernicus-support.ecmwf.int for further information.

**Comment by dwittig1** [comment]
thank you!

**Comment by ErikKusch** [comment]
Good luck and please update us! You might want to use KrigR from the development branch as we put a trial fix for this chunking of requests in there.

**Comment by dwittig1** [comment]
Thanks again Erik, It seems that it stops downloading after about 12 files. It is downloading about 8 months of data per file. R shows waiting for CDS to start processing the query. However, Copernicus just shows queued. Do you have any suggestions

**Comment by ErikKusch** [comment]
Afraid at this point I do not have any more suggestions than to clear your download queue in the CDS web portal and re-run your KrigR code
